name: Setup Magento Store

on:
  push:

jobs:
  setup-magento-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mage-os/github-actions/setup-magento
        with:
          php-version: 8.4
          tools: composer:v2
          mode: extension
          magento_version: 2.4.8-p3

      - run: composer config repositories.local path $GITHUB_WORKSPACE
        name: Add Github Repo for Testing
        working-directory: ${{ steps.setup-magento.outputs.path }}
        shell: bash

      - name: Run setup:di:compile
        uses: mage-os/github-actions/setup-di-compile@main
        with:
          php_version: "8.4"
